#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine to respect requirements
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx start
