#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine to respect requirements
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo chmod 644 /var/www/html/index.nginx-debian.html
sudo sed -i "48i \\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=oavMtUWDBTM;\n\t}\n" /etc/nginx/sites-available/default
sudo service nginx start
