#!/usr/bin/env bash
#A script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed (refer to the example)

i=$(ls)
for x in $i; 
do
	echo "$x" | cut -d'-' -f2
done
