#!/usr/bin/env bash
#Bash script that gives you information about the holbertonschool file

fil="holbertonschool"
if [ -e "$fil" ]
then
    echo "$fil file exists"
    if [ -s "$fil" ]
    then 
        echo "$fil file is not empty"
    else
        echo "$fil file is empty"
    fi
    if [ -f "$fil" ]
    then echo "$fil is a regular file"
    fi
else
echo "$fil file does not exist"
fi

